plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json

author: Jing Tian Feng
title: Jekytrap Playground Real Estate
tagline: Jekytrap Playground Real Estate
description: Jekytrap Playground Real Estate
url: https://jingtianfeng.github.io/jekytrap-playground-realestate
logo: /assets/img/logo.png
